[package]
name = "cracknuts_ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cracknuts_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
numpy = "0.25"
rayon = "1.10"
ndarray = "0.16"
